//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMIGO
    {
        public long AM_ID { get; set; }
        public Nullable<long> US_ID { get; set; }
        public Nullable<long> AM_US_IDA { get; set; }
        public string AM_TIPO { get; set; }
        public Nullable<System.DateTime> AM_FECHA { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
