//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMIGO
    {
        public long AM_ID { get; set; }
        public Nullable<long> US_ID { get; set; }
        public Nullable<long> AM_US_IDA { get; set; }
        public string AM_TIPO { get; set; }
        public Nullable<System.DateTime> AM_FECHA { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
