//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAN
    {
        public CLAN()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public long CL_ID { get; set; }
        public string CL_NOMBRE { get; set; }
        public Nullable<System.DateTime> CL_FCREACION { get; set; }
        public byte[] CL_AVATAR { get; set; }
        public string CL_DESCRIPCION { get; set; }
        public string CL_WWW { get; set; }
        public Nullable<bool> CL_PRIV { get; set; }
    
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
