//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedSocialEntities : DbContext
    {
        public RedSocialEntities()
            : base("name=RedSocialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AMIGO> AMIGO { get; set; }
        public DbSet<CLAN> CLAN { get; set; }
        public DbSet<DISPOSITIVO> DISPOSITIVO { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
    }
}
