//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedSocialEntities : DbContext
    {
        public RedSocialEntities()
            : base("name=RedSocialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AMIGO> AMIGO { get; set; }
        public DbSet<CLAN> CLAN { get; set; }
        public DbSet<DISPOSITIVO> DISPOSITIVO { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
        public DbSet<LOG> LOG { get; set; }
        public DbSet<UserRoles> UserRoles { get; set; }
    }
}
