//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPOSITIVO
    {
        public DISPOSITIVO()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public long DP_ID { get; set; }
        public string DP_MODELO { get; set; }
        public string DP_STATUS { get; set; }
        public string DP_SERIE { get; set; }
        public Nullable<System.DateTime> DP_FCREACION { get; set; }
        public Nullable<long> DP_PUNT { get; set; }
    
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
