//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPOSITIVO
    {
        public DISPOSITIVO()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public long DP_ID { get; set; }
        public string DP_MODELO { get; set; }
        public string DP_STATUS { get; set; }
        public string DP_SERIE { get; set; }
        public Nullable<System.DateTime> DP_FCREACION { get; set; }
        public Nullable<long> DP_PUNT { get; set; }
    
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
