//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID_LOG { get; set; }
        public Nullable<int> ID_DISPOSITIVO { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string TIPOMOV { get; set; }
        public Nullable<int> ID_USER_RECEPTOR { get; set; }
        public Nullable<int> CANT_PUNTOS { get; set; }
        public Nullable<System.DateTime> FECHAHORA { get; set; }
        public Nullable<int> ID_VEHICULO { get; set; }
        public Nullable<int> ID_CLAN { get; set; }
    }
}
