//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTenkiu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public long VE_ID { get; set; }
        public Nullable<long> US_ID { get; set; }
        public long CL_ID { get; set; }
        public long DP_ID { get; set; }
        public string VE_PATENTE { get; set; }
        public string VE_MARCA { get; set; }
        public string VE_MODELO { get; set; }
        public Nullable<int> VE_ANIO { get; set; }
        public string VE_COLOR { get; set; }
        public string VE_ESTADO { get; set; }
    
        public virtual CLAN CLAN { get; set; }
        public virtual DISPOSITIVO DISPOSITIVO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
